all: aufg1 aufg2 aufg3 aufg4 aufg6 hello_world

aufg1: aufg1.c
	 gcc -ansi -pedantic -Wall -o aufg1.exe aufg1.c
	 
aufg2: aufg2.c
	 gcc -ansi -pedantic -Wall -o aufg2.exe aufg2.c

aufg3: aufg3.c
	 gcc -ansi -pedantic -Wall -o aufg3.exe aufg3.c

aufg4: aufg4.c
	 gcc -ansi -pedantic -Wall -o aufg4.exe aufg4.c

aufg6: aufg6.c
	 gcc -ansi -pedantic -Wall -o aufg6.exe aufg6.c

clean:	
	rm *.exe